### ISSUE TITLE
Storybook 6.4.0 - TypeError: Cannot read properties of undefined (reading 'removeAllListeners')

### ISSUE THREAD

**Issue by Perni1984** [wKich/creevey#195]
When updating my project to storybook 6.4.0 I am getting a `TypeError: Cannot read properties of undefined (reading 'removeAllListeners')` error message when running creevey:

![image](https://user-images.githubusercontent.com/9039956/143680309-497a913a-1ce4-409d-8cb6-cfbdf04d6b31.png)

**Comment by Perni1984** [comment]
@wKich is there anything I could help with, or could you eventually point me in the right direction so I could provide a fix myself?

**Comment by giubatt** [comment]
+1 would be nice to be able to use storybook 6.4
We're using 6.3 for now as creevey is too useful for us compared to the alternatives

**Comment by vincentaudebert** [comment]
+1 we wanted to give a try to creevey but won't roll back to SB 6.3 just for this :(

**Comment by wKich** [comment]
Oh... I really didn't know, that so many projects use Creevey :) I'm so sorry folks for the huge delay. There were pretty busy the last few months. It's very hard to maintain the current flow for interactive tests and story extraction in Creevey (especially this one https://github.com/wKich/creevey/blob/master/src/server/loaders/babel/helpers.ts). So I want to simplify things a little bit, according to the new feature `interactive-stories`. There is no reason to parse stories and execute tests in Creevey's backend. All that I need to do is grab stories from a browser, provide capturing screenshot endpoint, so it can be executed from the browser. But the problem is, the test's format will be changed.

I'll try to do all my best to make Creevey works with SB6.4

**Comment by Perni1984** [comment]
@wKich if we can supply any PRs for any specific functionality or you can lay out a plan of how to do the migration we can contribute.

**Comment by Perni1984** [comment]
@wKich is there any documentation available on how to contribute. I tried to fork creevey to try to fix the problem myself, unfortunately I am a bit lost on how to even start creevey, because `yarn start` does not work on the main branch on my machine.

**Comment by mayank99** [comment]
> I am a bit lost on how to even start creevey, because `yarn start` does not work on the main branch on my machine.

@Perni1984 Maybe you need to install `run-p` globally as it's not included in dev deps.

**Comment by vincentaudebert** [comment]
Hi @wKich 

Just wondering if any progress has been made on this? Thanks a lot.

**Comment by wKich** [comment]
I appreciate you for all your patient.

I added support for CSFv3 and added `capture` API for `play()` method of story. https://github.com/wKich/creevey/pull/187

Soon there will be a small fix for Storybook 6.4 and then I'll release new beta version.

PS I know that I don't have so much time to maintain whole project, update docs, implement new features and promote it. Because it's not my primary job and I don't earn any profits from it except the support that I and how important Creevey became for all of you. So I'd like if someone has a little time to help me continue work on Creevey. Please join into [discord](https://discord.gg/p3um7DrxZK) so we are able to discuss any details. Even if you can't help with project, join too, so I'm able to ask your questions.

**Comment by mabry1985** [comment]
Hello, I am still seeing this issue. It looks like this was updated in 8.0-beta, but it seems like there was an issue with the build process and that was not packaged.

**Comment by Perni1984** [comment]
@mabry1985 you have to pull the beta via `yarn add creevey@next`

**Comment by mabry1985** [comment]
@Perni1984 oh perfect, thank you!
